apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deepanmurugan/servicetest.git
    targetRevision: HEAD
    path: nginx
    helm:
      releaseName: nginx-helm
      values: |
        replicaCount: 5
        nginxVersion: 1.16.2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 
