apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manage-dpop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deepanmurugan/servicetest.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
