apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deepanmurugan/servicetest.git
    targetRevision: HEAD
    path: httpd
    helm:
      releaseName: httpd-helm
      values: |
        replicaCount: 3
        httpdVersion: 2.4
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 
